In [1]:
import numpy as np

In [2]:
cli = np.genfromtxt('climate.txt',delimiter= ',', skip_header= 1)# txt to np array

In [3]:
cli

array([[ 34.,  23.,  55.],
       [ 51.,  48.,  37.],
       [ 33.,  89.,  31.],
       [ 95.,  74.,  24.],
       [ 23.,  31.,  47.],
       [ 49.,  84.,  97.],
       [ 23.,  91.,  45.],
       [ 89.,  73.,  48.],
       [ 77.,  95.,  55.],
       [ 20.,  40.,  74.],
       [ 63.,  55.,  39.],
       [ 47.,  63.,  33.],
       [ 31.,  68.,  32.],
       [ 65.,  64.,  97.],
       [ 53.,  25.,  78.],
       [ 88.,  35.,  68.],
       [ 30.,  90.,  57.],
       [ 66.,  93.,  44.],
       [ 28.,  25.,  49.],
       [ 57.,  30.,  49.],
       [ 32.,  68.,  55.],
       [ 78.,  66.,  40.],
       [ 67.,  65.,  46.],
       [ 54.,  29.,  97.],
       [ 41.,  88.,  51.],
       [ 40.,  79.,  68.],
       [ 54.,  91.,  48.],
       [ 61.,  27.,  49.],
       [ 24.,  60.,  71.],
       [ 54.,  28.,  47.],
       [ 92.,  60.,  47.],
       [ 83.,  70.,  78.],
       [ 38.,  53.,  37.],
       [ 51.,  91.,  88.],
       [ 53.,  94.,  74.],
       [ 94.,  71.,  66.],
       [ 48.,  37.,  85.],
 

In [4]:
wt = np.array([0.3,0.2,0.5])

In [5]:
# @ -> matrix * operator, both need tobe in the form of np.array
y = cli @ wt
y

array([42.3, 43.4, 43.2, 55.3, 36.6, 80. , 47.6, 65.3, 69.6, 51. , 49.4,
       43.2, 38.9, 80.8, 59.9, 67.4, 55.5, 60.4, 37.9, 47.6, 50.7, 56.6,
       56.1, 70.5, 55.4, 61.8, 58.4, 48.2, 54.7, 45.3, 63.1, 77.9, 40.5,
       77.5, 71.7, 75.4, 64.3, 44.1, 68. , 74.8, 56.2, 67.1, 48.2, 68.7,
       59.1, 37.6, 53.7, 81.8, 82.7, 54.8, 73.3, 55.7, 46. , 56.6, 64.1,
       56. , 44. , 71.8, 66.4, 76.1, 60.8, 78.3, 55.6, 51.5, 70.6, 57.7,
       61.8, 31.9, 34.1, 63. , 78.5, 75.9, 74.2, 46.4, 57.1, 76.1, 27.7,
       50.4, 46.1, 60.3, 58.3, 48.4, 56.8, 36.1, 39.8, 78.5, 41.8, 35.9,
       70.3, 77.1, 54.4, 40. , 59.5, 36.4, 86.4, 47.6, 53. , 41.6, 46.7,
       84.8])

In [6]:
# append it back to climate.txt file
c_r = np.concatenate((cli,y.reshape(100,1)) , axis = 1)

In [7]:
c_r

array([[ 34. ,  23. ,  55. ,  42.3],
       [ 51. ,  48. ,  37. ,  43.4],
       [ 33. ,  89. ,  31. ,  43.2],
       [ 95. ,  74. ,  24. ,  55.3],
       [ 23. ,  31. ,  47. ,  36.6],
       [ 49. ,  84. ,  97. ,  80. ],
       [ 23. ,  91. ,  45. ,  47.6],
       [ 89. ,  73. ,  48. ,  65.3],
       [ 77. ,  95. ,  55. ,  69.6],
       [ 20. ,  40. ,  74. ,  51. ],
       [ 63. ,  55. ,  39. ,  49.4],
       [ 47. ,  63. ,  33. ,  43.2],
       [ 31. ,  68. ,  32. ,  38.9],
       [ 65. ,  64. ,  97. ,  80.8],
       [ 53. ,  25. ,  78. ,  59.9],
       [ 88. ,  35. ,  68. ,  67.4],
       [ 30. ,  90. ,  57. ,  55.5],
       [ 66. ,  93. ,  44. ,  60.4],
       [ 28. ,  25. ,  49. ,  37.9],
       [ 57. ,  30. ,  49. ,  47.6],
       [ 32. ,  68. ,  55. ,  50.7],
       [ 78. ,  66. ,  40. ,  56.6],
       [ 67. ,  65. ,  46. ,  56.1],
       [ 54. ,  29. ,  97. ,  70.5],
       [ 41. ,  88. ,  51. ,  55.4],
       [ 40. ,  79. ,  68. ,  61.8],
       [ 54. ,  91. ,  48. ,  58.4],
 

In [8]:
np.savetxt('cr.txt',
          c_r,
          fmt='%.2f',
          header='temperature, rainfall, humidity, yeild_apples',
          comments='')

In [9]:
'''
. Mathematics: np.sum, np.exp, np.round, arithemtic operators, comparision ops
. Array manipulation: np.reshape, np.stack, np.concatenate, np.split
. Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
. Statistics: np.mean, np.median, np.std, np.max
'''


arr2 = np.array([[1, 2, 3, 4],
                [5,6,7,8],
                [9,1,2,3]])

arr3 = np.array([[11, 12, 13, 14],
                [15,16,17,18],
                [19, 11, 12, 13]])

In [10]:
print(arr2-3)

[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6 -2 -1  0]]


In [11]:
print(arr3-arr2)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [12]:
arr2 = np.array([[1, 2, 3, 4],
                [5,6,7,8],
                [9,1,2,3]])

arr3 = np.array([4,5,6,7])
arr2 + arr3 # completely valid  -----> broadcasting only works when an array can be formed by replicating the other one


array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [13]:

arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [14]:
arr1 == arr2


array([[False,  True,  True],
       [False, False,  True]])

In [15]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [16]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [17]:
# to check matching nums in an array:
(arr1 == arr2).sum()

3

In [19]:
# indexing and slicing
arr3 = np.array ([
[[11, 12, 13, 14],
[13, 14, 15, 19]],

[[15,16,17,21],
[63, 92, 36, 18]],

[[98,32, 81, 23],
[17, 18, 19.5, 43]]])

# single element
arr3[1,1,2]

36.0

In [20]:
# subarray using ranges

arr3[1:,0:1,:2]
# 15,16,98,32

array([[[15., 16.]],

       [[98., 32.]]])

ways to create numpy arrays:

In [21]:
 # all zeros
np.zeros((3,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
 # all ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# random vector
np.random.rand(5)

array([0.04484334, 0.63604298, 0.12779069, 0.27819506, 0.85127888])

In [28]:
# random matrix
np.random.randn(2,3)

# rand picks between 0,1
# rand n picks from gaussian probability distribution  ---> mern of 0, std dev of 1

array([[ 0.24481637,  0.79771361, -1.21444739],
       [ 0.09234899, -0.55556148, -0.29823907]])

In [29]:
# fixed value
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [34]:
# range with start , end, space
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [37]:
np.arange(10,90,3).shape
np.arange(10,90,3).reshape(3,3,3)
np.arange(10,90,3).reshape(3,3,-1)
# both are same

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [33]:
# equally spaced no. in a range
np.linspace(3,27,9)# 9 in no. of elements we want

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])